[build]
  command = "pnpm run build"
  publish = "build/client"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
