[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[edge_functions]]
  function = "server"
  path = "/*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
